app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['as'=>'home', 'uses'=>'SiteController@index']);
Route::get('quem-somos', ['as'=>'quemSomos', 'uses'=>'SiteController@quemSomos']);

# Forms
Route::get('contato', ['as'=>'contato', 'uses'=>'SiteController@contato']);
Route::post('contato', ['as'=>'contato.post', 'uses'=>'SiteController@postContato']);

# Passwords
Route::get('password/reset', ['uses' => 'PasswordController@remind',  'as' => 'password.remind']);
Route::post('password/reset', ['uses' => 'PasswordController@request', 'as' => 'password.request']);
Route::get('password/reset/{token}', ['uses' => 'PasswordController@reset', 'as' => 'password.reset']);
Route::post('password/reset/{token}', ['uses' => 'PasswordController@update', 'as' => 'password.update']);



//Route::get('portfolio-de-atividades', ['as'=>'atividades', 'uses'=>'SiteController@atividades']);
Route::get('descontos', ['as'=>'descontos', 'uses'=>'SiteController@descontos']);
//Route::get('minha-sacola', ['as'=>'minhaSacola', 'uses'=>'SiteController@minhaSacola']);
Route::get('recuperar-senha', ['as'=>'recuperarSenha', 'uses'=>'SiteController@recuperarSenha']);
Route::get('resultado-busca', ['as'=>'resultadoBusca', 'uses'=>'SiteController@resultadoBusca']);

# Events
Route::get('evento/{slug}', ['as'=>'events.show', 'uses'=>'ProductsController@show']);
Route::get('produtos/{tax}/{category?}', ['as'=>'events.index', 'uses'=>'ProductsController@results']);

# Users/customers
Route::get('cadastro', ['as'=>'user.register', 'uses'=>'UsersController@register']);
Route::post('cadastro', ['as'=>'user.register.post', 'uses'=>'UsersController@postRegister']);
Route::get('cadastro/resultado', ['as'=>'user.register.return', 'uses'=>'UsersController@result']);
Route::get('cadastro/confirmacao/{activationCode}', ['as'=>'user.register.activation', 'uses'=>'UsersController@activation']);

Route::post('login',['as'=>'user.login', 'uses'=>'UsersController@login']);
Route::get('logout',['as'=>'user.logout', 'uses'=>'UsersController@logout']);

# User account area
Route::group(['before'=>'auth'], function(){
	Route::get('minha-conta',['as'=>'user.edit', 'uses'=>'UsersController@edit']);
	Route::post('minha-conta',['as'=>'user.update', 'uses'=>'UsersController@update']);

	# Meus eventos
	Route::get('eventos', ['as'=>'user.events', 'uses'=>'UsersController@events']);

	# Reset senha
	Route::post('password/reset', ['uses' => 'PasswordController@userUpdate', 'as' => 'user.password.update']);

	# Compras
	Route::post('adiciona/{event_id}', ['as'=>'event.add', 'uses'=>'SubscriptionsController@addCart']);
	Route::get('minha-sacola', ['as'=>'subscription.create', 'uses'=>'SubscriptionsController@create']);
	Route::post('retira/item/{event_id}', ['as'=>'cart.delete.item', 'uses'=>'SubscriptionsController@deleteItem']);
	Route::post('atualiza/item/{event_id}', ['as'=>'cart.update.item', 'uses'=>'SubscriptionsController@updateItem']);
});

# Imprensa
Route::get('imprensa', ['as'=>'imprensa.index', 'uses'=>'NoticesController@siteIndex']);
Route::get('imprensa/{id}', ['as'=>'imprensa.show', 'uses'=>'NoticesController@show']);

# Admin
Route::get('admin', ['as'=>'admin.index', 'before'=>'already.log.admin', 'uses'=>'AdminController@index']);
Route::post('admin', ['as'=>'admin.login', 'uses'=>'AdminController@login']);
Route::get('admin/logout', ['as'=>'admin.logout', 'uses'=>'AdminController@logout']);

Route::group(['prefix'=>'admin', 'before'=>'auth|auth.admin'], function(){
	
	# Eventos
	Route::resource('eventos', 'ProductsController');
	
	# Facilitadores
	Route::resource('facilitator', 'FacilitatorsController');

	# Áreas
	Route::resource('areas', 'CategoriesController');

	# Taxonomias
	Route::resource('taxonomias', 'TaxonomiesController');

	# Clientes
	Route::resource('clientes', 'UsersController');

	# Instituições
	Route::resource('instituicoes', 'InstitutionsController');

	# Imprensa
	Route::resource('imprensa', 'NoticesController');

	# Titulos
	Route::resource('titulos', 'TitlesController');

	# Newsletters
	Route::resource('newsletters', 'NewslettersController');

	# Banners
	Route::resource('banners', 'BannersController');
	
	# Apoiadores
	Route::resource('apoiadores', 'ApoiadoresController');
});

# Searches
Route::post('city/search', ['as'=>'city.search', 'uses'=>'CitiesController@searchByState']);

Route::get('meus-dados', ['as'=>'meusDados', 'uses'=>'SiteController@meusDados']);
Route::get('meus-pedidos', ['as'=>'meusPedidos', 'uses'=>'SiteController@meusPedidos']);

app/views/admin/events/create.blade.php
@extends('layouts.admin')
@section('content')
	
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Eventos <small>Criar novo</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> Evento
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-md-8">
                        
                        @include('layouts.notifications')

                        {{ Form::open(['route'=>'admin.eventos.store', 'files'=>true]) }}
                        <table class="table table-bordered table-striped">
                            <tr>
                                <td>Imagem</td>
                                <td>{{ Form::file('src') }}</td>
                            </tr>
                            <tr>
                                <td>Destaque (não obrigatório)</td>
                                <td>
                                    {{ Form::radio('featured', 4) }} Hiper-destaque 
                                    {{ Form::radio('featured', 2) }} Mega-destaque 
                                    {{ Form::radio('featured', 3) }} Destaque
                                </td>
                            </tr>
                             <tr>
                                <td>Nome *</td>
                                <td>{{ Form::select('title_id', [''=>'Selecione']+$titles, null, ['class'=>'form-control']) }}</td>
                            </tr>
                             <tr>
                                <td>Nome Complementar </td>
                                <td>{{ Form::text('name', null, ['class'=>'form-control']) }}</td>
                            </tr>
                             <tr>
                                <td>Tipologia *</td>
                                <td>{{ Form::select('category_id', [''=>'Selecione']+$categories, null, ['class'=>'form-control']) }}</td>
                            </tr>
                             <tr>
                                <td>Facilitador *</td>
                                <td>{{ Form::select('facilitator_id', [''=>'Selecione']+$facilitators, null, ['class'=>'form-control']) }}</td>
                            </tr>
                             <tr>
                                <td>Local</td>
                                <td>
                                    <table class="table">
                                        <tr>
                                            <td>Endereço *</td>
                                            <td>{{ Form::text('address', null, ['class'=>'form-control']) }}</td>
                                        </tr>
                                         <tr>
                                            <td>Numero *</td>
                                            <td>{{ Form::number('number', null, ['class'=>'form-control']) }}</td>
                                        </tr>
                                        <tr>
                                            <td>Complemento *</td>
                                            <td>{{ Form::text('complement', null, ['class'=>'form-control']) }}</td>
                                        </tr>
                                        <tr>
                                            <td>Estado *</td>
                                            <td>{{ Form::select('state_id', [''=>'UF']+$states, null, ['class'=>'form-control', 'id'=>'state_id']) }}</td>
                                        </tr>
                                        <tr>
                                            <td>Cidade *</td>
                                            <td>{{ Form::select('city_id', [''=>'Selecione cidade'], null, ['class'=>'form-control', 'id'=>'city_id']) }}</td>
                                        </tr>
                                        <tr>
                                            <td>Bairro *</td>
                                            <td>{{ Form::text('district', null, ['class'=>'form-control']) }}</td>
                                        </tr>
                                      
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>Data início *</td>
                                <td>{{ Form::text('date_ini', null, ['class'=>'form-control datepicker'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Data término *</td>
                                <td>{{ Form::text('date_fin', null, ['class'=>'form-control datepicker'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Hora *</td>
                                <td>{{ Form::text('hour', null, ['class'=>'form-control'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Duração *</td>
                                <td>{{ Form::text('duration', null, ['class'=>'form-control'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Data limite de inscrição</td>
                                <td>{{ Form::text('date_event_register_limit', null, ['class'=>'form-control'] ) }}</td>
                            </tr>
                              <tr>
                                <td>Preço *</td>
                                <td>{{ Form::text('price', null, ['class'=>'form-control'] ) }}</td>
                            </tr>
                            <tr>
                                <td>Conteúdo *</td>
                                <td>{{ Form::textarea('content', null, ['class'=>'form-control ckeditor'] ) }}</td>
                            </tr>
                            <tr>
                                <td>Informação de desconto</td>
                                <td>{{ Form::textarea('info_discount', null, ['class'=>'form-control'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Currículo anexo *</td>
                                <td>{{ Form::file('curriculum') }}</td>
                            </tr>
                            <tr>
                                <td>Eventos relacionados *</td>
                                <td>{{ Form::select('related_events[]', $events, null, ['class'=>'form-control', 'multiple', 'style'=>'height:200px;']) }}</td>
                            </tr>
                            <tr>
                                <td>Ativo</td>
                                <td>{{ Form::checkbox('active', 1, true) }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="text-right">
                                    {{ Form::submit('Enviar', ['class'=>'btn btn-primary']) }}
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
@stop

app/views/admin/events/edit.blade.php
@extends('layouts.admin')
@section('content')
    
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Eventos <small>Editar</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li class="active">
                                <i class="fa fa-dashboard"></i> {{ $event->name }}
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-md-8">
                        
                        @include('layouts.notifications')

                        {{ Form::open(['route'=>array('admin.eventos.update', $event->id), 'method'=>'put', 'files'=>true]) }}
                        <table class="table table-bordered table-striped">
                            <tr>
                                <td>Imagem</td>
                                <td>
                                    {{ HTML::image('uploads/eventos/thumb/'.$event->src) }} 
                                    {{ Form::file('src') }}</td>
                            </tr>
                            <tr>
                                <td>Destaque (não obrigatório)</td>
                                <td>
                                    {{ Form::radio('featured', 4, $check_1) }} Hiper-destaque 
                                    {{ Form::radio('featured', 2, $check_2) }} Mega-destaque 
                                    {{ Form::radio('featured', 3, $check_3) }} Destaque
                                </td>
                            </tr>
                             <tr>
                                <td>Nome *</td>
                                <td>{{ Form::select('title_id', [''=>'Selecione']+$titles, $event->title_id, ['class'=>'form-control']) }}</td>
                            </tr>
                        
                             <tr>
                                <td>Nome Complementar</td>
                                <td>{{ Form::text('name', $event->name, ['class'=>'form-control']) }}</td>
                            </tr>
                             <tr>
                                <td>Tipologia *</td>
                                <td>{{ Form::select('category_id', [''=>'Selecione']+$categories, $event->category_id, ['class'=>'form-control']) }}</td>
                            </tr>
                             <tr>
                                <td>Facilitador *</td>
                                <td>{{ Form::select('facilitator_id', [''=>'Selecione']+$facilitators, $event->facilitator_id, ['class'=>'form-control']) }}</td>
                            </tr>
                             <tr>
                                <td>Local</td>
                                <td>
                                    <table class="table">
                                        <tr>
                                            <td>Endereço *</td>
                                            <td>{{ Form::text('address', $event->address, ['class'=>'form-control']) }}</td>
                                        </tr>
                                         <tr>
                                            <td>Numero *</td>
                                            <td>{{ Form::number('number', $event->number, ['class'=>'form-control']) }}</td>
                                        </tr>
                                        <tr>
                                            <td>Complemento *</td>
                                            <td>{{ Form::text('complement', $event->complement, ['class'=>'form-control']) }}</td>
                                        </tr>
                                        <tr>
                                            <td>Estado *</td>
                                            <td>{{ Form::select('state_id', [''=>'UF']+$states, $event->city->state->id, ['class'=>'form-control', 'id'=>'state_id']) }}</td>
                                        </tr>
                                        <tr>
                                            <td>Cidade *</td>
                                            <td>{{ Form::select('city_id', [''=>'Selecione cidade']+$cities, $event->city_id, ['class'=>'form-control', 'id'=>'city_id']) }}</td>
                                        </tr>
                                        <tr>
                                            <td>Bairro *</td>
                                            <td>{{ Form::text('district', $event->district, ['class'=>'form-control']) }}</td>
                                        </tr>
                                      
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td>Data início *</td>
                                <td>{{ Form::text('date_ini', Helper::ConverterBR($event->date_ini), ['class'=>'form-control datepicker'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Data término *</td>
                                <td>{{ Form::text('date_fin', Helper::ConverterBR($event->date_fin), ['class'=>'form-control datepicker'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Hora *</td>
                                <td>{{ Form::text('hour', $event->hour, ['class'=>'form-control'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Duração *</td>
                                <td>{{ Form::text('duration', $event->duration, ['class'=>'form-control'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Data limite de inscrição</td>
                                <td>{{ Form::text('date_event_register_limit', Helper::ConverterBR($event->date_event_register_limit), ['class'=>'form-control'] ) }}</td>
                            </tr>
                              <tr>
                                <td>Preço *</td>
                                <td>{{ Form::text('price', $event->price, ['class'=>'form-control'] ) }}</td>
                            </tr>
                            <tr>
                                <td>Conteúdo *</td>
                                <td>{{ Form::textarea('content', $event->content, ['class'=>'form-control ckeditor'] ) }}</td>
                            </tr>
                            <tr>
                                <td>Informação de desconto</td>
                                <td>{{ Form::textarea('info_discount', $event->info_discount, ['class'=>'form-control'] ) }}</td>
                            </tr>
                             <tr>
                                <td>Currículo anexo *</td>
                                <td>{{ Form::file('curriculum') }}</td>
                            </tr>
                            <tr>
                                <td>Eventos relacionados *</td>
                                <td>{{ Form::select('related_events[]', $events, $related_events, ['class'=>'form-control', 'multiple', 'style'=>'height:200px;']) }}</td>
                            </tr>
                            <tr>
                                <td>Ativo</td>
                                <td>{{ Form::checkbox('active', 1, true) }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="text-right">
                                    {{ Form::submit('Enviar', ['class'=>'btn btn-primary']) }}
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
@stop

app/views/admin/events/index.blade.php
@extends('layouts.admin')
@section('content')
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Eventos <small>({{ $events->getTotal() }})</small>
        </h1>
    </div>
</div>
<!-- /.row -->
<div class="col-md-12">
	<div class="alert alert-info text-right">
		<a href="{{ route('admin.eventos.create') }}" class="btn btn-primary "><i class="fa fa-plus"></i> NOVO</a>
	</div>
	
	 @include('layouts.notifications')

	@if($events->count() > 0)
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
			<tr>
				<th>Imagem</th>
				<th>Título</th>
				<th>Tipo</th>
				<th>Endereço</th>
				<th>Datas/Horários</th>
				<th>Ativo</th>
				<th>Editar</th>
				<th>Apagar</th>
			</tr>
			@foreach($events as $e)
			<tr>			
				<td>{{ HTML::image('uploads/eventos/'.$e->src, $e->name, ['height'=>80]) }}</td>
				<td>{{ $e->name }}</td>
				<td>{{ $e->category->name }}</td>
				<td>{{ $e->address }}, {{ $e->number }} {{ $e->complement or null }}, {{ $e->district }}, {{ $e->city->name or null }} - {{ $e->city->state->uf or null }}</td>
				<td>
					@if($e->date_ini != '')
					{{ Helper::ConverterBR($e->date_ini) }} até {{ Helper::ConverterBR($e->date_fin) }} das {{ $e->hour }}
					@endif
				</td>
				<td>{{ $e->active == '1' ? 'Sim' : 'Não' }}</td>
				<td>
					<a href="{{ route('admin.eventos.edit', ['id'=>$e->id]) }}"><i class="fa fa-edit"></i></a>
				</td>
				<td>
					{{ Form::open(['route'=>array('admin.eventos.destroy', 'id'=>$e->id), 'method'=>'delete']) }}
					<button type="submit">
		                <i class="fa fa-trash"></i>
		            </button>
					
					{{ Form::close() }}
				</td>
			</tr>
			@endforeach
		</table>
		{{ $events->appends($_GET)->links() }}
	</div>
	@else
	<div class="alert alert-warning">
		<p><i class="fa fa-marker"></i> Ainda não temos conteúdo para esta área</p>
	</div>
	@endif
</div>
@stop